export const HANDLE_TEXT_CHANGE_PATIENT = 'HANDLE_TEXT_CHANGE_PATIENT';
export const PATIENT_VALIDATION = 'PATIENT_VALIDATION';
export const RESET_PATIENT = 'RESET_PATIENT';
export const GET_PATIENT = 'GET_PATIENT';
